import { getCategory, type CategoryId } from "./categories";
import { normalizeMilestones } from "./milestones";
import { DEFAULT_MONEY_SETTINGS, validateMoneySettings, type MoneySettings } from "./money";
import { err, ok, type Result } from "./result";
import { isValidInstant, type Instant } from "./time";
import type { Journey, Period, RelapseEvent, UrgeEvent, UrgeOutcome } from "./types";

/**
 * Journey commands. All functions are pure: they validate input and return a new Journey,
 * never mutating the old one. Identifiers are generated by the caller so that a command
 * retried with the same id (double tap, re-submit) is rejected instead of duplicated.
 */

export const MAX_NOTE_LENGTH = 2_000;
export const MAX_TAGS = 10;
export const MAX_TAG_LENGTH = 40;
export const MAX_URGE_DURATION_MINUTES = 24 * 60;
export const MIN_INTENSITY = 1;
export const MAX_INTENSITY = 10;

export type InstantError = "invalid_instant" | "in_future";
export type TextError = "note_too_long" | "invalid_tags";

export function currentPeriod(journey: Journey): Period | null {
  const last = journey.periods.at(-1);
  return last && last.endedAt === null ? last : null;
}

function checkInstant(value: Instant, now: Instant): InstantError | null {
  if (!isValidInstant(value)) return "invalid_instant";
  if (value > now) return "in_future";
  return null;
}

function normalizeNote(note: string | null | undefined): Result<string | null, TextError> {
  const trimmed = note?.trim() ?? "";
  if (trimmed.length > MAX_NOTE_LENGTH) return err("note_too_long");
  return ok(trimmed === "" ? null : trimmed);
}

function checkTags(tags: readonly string[]): TextError | null {
  const valid =
    tags.length <= MAX_TAGS && tags.every((t) => t.length > 0 && t.length <= MAX_TAG_LENGTH);
  return valid ? null : "invalid_tags";
}

// ---------------------------------------------------------------------------------------

export interface CreateJourneyInput {
  id: string;
  periodId: string;
  categoryId: CategoryId;
  startedAt: Instant;
  now: Instant;
  milestoneHours?: readonly number[];
  money?: MoneySettings;
}

export type CreateJourneyError =
  InstantError | "category_unavailable" | "invalid_milestones" | "invalid_money_settings";

export function createJourney(input: CreateJourneyInput): Result<Journey, CreateJourneyError> {
  const category = getCategory(input.categoryId);
  if (category.status !== "available") return err("category_unavailable");
  const instantError = checkInstant(input.startedAt, input.now);
  if (instantError) return err(instantError);
  const milestones = normalizeMilestones(input.milestoneHours ?? category.defaultMilestoneHours);
  if (!milestones.ok) return err("invalid_milestones");
  const money = validateMoneySettings(input.money ?? DEFAULT_MONEY_SETTINGS);
  if (!money.ok) return err("invalid_money_settings");

  return ok({
    id: input.id,
    categoryId: input.categoryId,
    createdAt: input.now,
    periods: [{ id: input.periodId, startedAt: input.startedAt, endedAt: null, endReason: null }],
    relapses: [],
    urges: [],
    milestoneHours: milestones.value,
    money: money.value,
  });
}

// ---------------------------------------------------------------------------------------

export interface RecordRelapseInput {
  relapseId: string;
  newPeriodId: string;
  occurredAt: Instant;
  /** When the new period starts; defaults to `occurredAt`. */
  restartAt?: Instant;
  contributingFactors?: readonly string[];
  note?: string | null;
  now: Instant;
}

export type RecordRelapseError =
  | InstantError
  | TextError
  | "no_open_period"
  | "before_period_start"
  | "restart_before_relapse"
  | "duplicate_id";

/**
 * Closes the open period at `occurredAt` and opens a new one. Previous periods, urges,
 * relapses and the milestones they reached are kept untouched.
 */
export function recordRelapse(
  journey: Journey,
  input: RecordRelapseInput,
): Result<Journey, RecordRelapseError> {
  const open = currentPeriod(journey);
  if (!open) return err("no_open_period");
  if (
    journey.relapses.some((r) => r.id === input.relapseId) ||
    journey.periods.some((p) => p.id === input.newPeriodId)
  ) {
    return err("duplicate_id");
  }
  const occurredError = checkInstant(input.occurredAt, input.now);
  if (occurredError) return err(occurredError);
  if (input.occurredAt < open.startedAt) return err("before_period_start");
  const restartAt = input.restartAt ?? input.occurredAt;
  const restartError = checkInstant(restartAt, input.now);
  if (restartError) return err(restartError);
  if (restartAt < input.occurredAt) return err("restart_before_relapse");
  const factors = input.contributingFactors ?? [];
  const tagError = checkTags(factors);
  if (tagError) return err(tagError);
  const note = normalizeNote(input.note);
  if (!note.ok) return note;

  const closed: Period = { ...open, endedAt: input.occurredAt, endReason: "relapse" };
  const next: Period = {
    id: input.newPeriodId,
    startedAt: restartAt,
    endedAt: null,
    endReason: null,
  };
  const relapse: RelapseEvent = {
    id: input.relapseId,
    periodId: open.id,
    occurredAt: input.occurredAt,
    recordedAt: input.now,
    contributingFactors: factors,
    note: note.value,
  };
  return ok({
    ...journey,
    periods: [...journey.periods.slice(0, -1), closed, next],
    relapses: [...journey.relapses, relapse],
  });
}

// ---------------------------------------------------------------------------------------

export interface RecordUrgeInput {
  id: string;
  occurredAt: Instant;
  intensity: number;
  trigger?: string | null;
  durationMinutes?: number | null;
  copingActions?: readonly string[];
  outcome: UrgeOutcome;
  note?: string | null;
  now: Instant;
}

export type RecordUrgeError =
  InstantError | TextError | "invalid_intensity" | "invalid_duration" | "duplicate_id";

/**
 * Logs an urge. An urge with outcome "acted" does not close the period by itself: the UI
 * offers the relapse flow so that the user stays in control of what is recorded.
 */
export function recordUrge(
  journey: Journey,
  input: RecordUrgeInput,
): Result<Journey, RecordUrgeError> {
  if (journey.urges.some((u) => u.id === input.id)) return err("duplicate_id");
  const instantError = checkInstant(input.occurredAt, input.now);
  if (instantError) return err(instantError);
  if (
    !Number.isInteger(input.intensity) ||
    input.intensity < MIN_INTENSITY ||
    input.intensity > MAX_INTENSITY
  ) {
    return err("invalid_intensity");
  }
  const duration = input.durationMinutes ?? null;
  if (
    duration !== null &&
    (!Number.isInteger(duration) || duration < 0 || duration > MAX_URGE_DURATION_MINUTES)
  ) {
    return err("invalid_duration");
  }
  const trigger = input.trigger ?? null;
  const copingActions = input.copingActions ?? [];
  const tagError = checkTags(trigger === null ? copingActions : [trigger, ...copingActions]);
  if (tagError) return err(tagError);
  const note = normalizeNote(input.note);
  if (!note.ok) return note;

  const urge: UrgeEvent = {
    id: input.id,
    occurredAt: input.occurredAt,
    recordedAt: input.now,
    intensity: input.intensity,
    trigger,
    durationMinutes: duration,
    copingActions,
    outcome: input.outcome,
    note: note.value,
  };
  return ok({ ...journey, urges: [...journey.urges, urge] });
}

// ---------------------------------------------------------------------------------------

export type EditStartError = InstantError | "no_open_period" | "before_previous_period";

/** Corrects the start of the open period (e.g. the user picked the wrong date). */
export function editCurrentPeriodStart(
  journey: Journey,
  startedAt: Instant,
  now: Instant,
): Result<Journey, EditStartError> {
  const open = currentPeriod(journey);
  if (!open) return err("no_open_period");
  const instantError = checkInstant(startedAt, now);
  if (instantError) return err(instantError);
  const previous = journey.periods.at(-2);
  if (previous?.endedAt != null && startedAt < previous.endedAt) {
    return err("before_previous_period");
  }
  return ok({ ...journey, periods: [...journey.periods.slice(0, -1), { ...open, startedAt }] });
}

export function updateMoneySettings(
  journey: Journey,
  money: MoneySettings,
): Result<Journey, "invalid_money_settings"> {
  const valid = validateMoneySettings(money);
  return valid.ok ? ok({ ...journey, money: valid.value }) : err("invalid_money_settings");
}

export function updateMilestones(
  journey: Journey,
  milestoneHours: readonly number[],
): Result<Journey, "invalid_milestones"> {
  const normalized = normalizeMilestones(milestoneHours);
  return normalized.ok
    ? ok({ ...journey, milestoneHours: normalized.value })
    : err("invalid_milestones");
}
